name: Terraform GitOps

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_branch:
        description: ''
        required: true
        type: choice
        options:
          - main
          - dev
jobs:
  s3_setup_and_terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 
      - name: Check to see if S3 bucket exist
        id: check_s3_bucket
        run: | 
           if aws s3 ls s3://my-terraform-state-bucket-75445365/ > /dev/null 2>&1; then
             ehco "::set-output name=s3_bucket_exists::true"
           else
             echo "::set-output name=s3_bucket_exists::false"
           fi
      - name: Create S3 Bucket
        if: steps.check_s3_bucket.outputs.s3_bucket_exists == 'false'
        run: | 
          aws s3 mb s3://my-terraform-state-bucket-75445365/ --region ${{env.REGION}}
      - name: Terraform fmt
        run: terraform fmt -check